domain: whale-ofatime.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://whale-ofatime.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /WotVAccuracyCalculator     # place folder name if the site is served in a subfolder
description: War of the Visions Accuracy Calculator

title: WotV Accuracy Calculator
iconURL: assets/default-icon.png
remote_theme: supunkavinda/jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: _SupunKavinda
  github: SupunKavinda

plugins:
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N